services:
  - type: web
    name: acesms-backend
    env: node
    plan: free
    region: oregon
    branch: main
    buildCommand: 'npm install'
    startCommand: 'npm start'
    envVars:
      - key: ACESMS_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_EMAIL
        sync: false
